# version: "3"
# services:
#   web:
#     container_name: web
#     build: .
#     restart: always
#     ports:
#       - "8082:8082"
#       - "9229:9299"
#     links:
#       - mongo
#   mongo:
#     container_name: mongo
#     image: mongo
#     volumes:
#       - ./data:/data/db
#     ports:
#       - '27018:27017'

version: '3'
services:
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - '27017:27017'

